### PR TITLE
Fix progress in IE and dialogs in FF and Safari

### LINKED ISSUE #148: core-progress: wrong value in IE11 with React
`<CoreProgress className="tv-pages-progress-bar" value={50} min={0} max={100} />`
gives
`<progress class="tv-pages-progress-bar" role="img" aria-label="50%" value="1" max="100" min="0" data-nrk-core-progress-1-0-0="50"></progress>`

### PR DESCRIPTION
**Pull request by eirikbacker**
Resolves #148 and #147

### CODE REVIEW

File: packages/core-dialog/core-dialog.js [hunk 1]
```diff
@@ -22,11 +22,10 @@ export default function dialog (dialogs, open) {
     const isStrict = typeof options.strict === 'boolean' ? options.strict : dialog.getAttribute(UUID) === 'true'
 
     dialog.setAttribute(UUID, isStrict)
-    dialog.setAttribute('tabindex', -1)
     dialog.setAttribute('role', 'dialog')
     dialog.setAttribute('aria-modal', true)
-    dialog.setAttribute('aria-label', options.label || dialog.getAttribute('aria-label'))
-    hasBackdrop || dialog.insertAdjacentElement('afterend', document.createElement('backdrop'))
+    // dialog.setAttribute('aria-label', options.label || dialog.getAttribute('aria-label'))
```
Comment (eirikbacker) [inline packages/core-dialog/core-dialog.js]: Need a word with @kristofferlium about this
